 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: flasknode
 spec:
   replicas: 3
   selector:
     matchLabels:
       app: flasknode
   template:
     metadata:
       labels:
         app: flasknode
     spec:
       containers:
       - name: flasknode
         image: icr.io/bergin/my-repo
         imagePullPolicy: Always
         ports:
         - containerPort: 9000
